// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs6Y0UDuXRclDck6eyMT6h3yJ7k2o4CWg',
    appId: '1:31424277853:web:8594fbc6995bd74b4a8cb4',
    messagingSenderId: '31424277853',
    projectId: 'contador-calorias-b7dc8',
    authDomain: 'contador-calorias-b7dc8.firebaseapp.com',
    storageBucket: 'contador-calorias-b7dc8.firebasestorage.app',
    measurementId: 'G-532P3YCZL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4XZgRn9Gt7InrGIJedmc4ch6ypHvcpb8',
    appId: '1:31424277853:android:50b50bb0bcde355a4a8cb4',
    messagingSenderId: '31424277853',
    projectId: 'contador-calorias-b7dc8',
    storageBucket: 'contador-calorias-b7dc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl3FFMoOfMMDQK0jvb3BxeJr3v4OiaUy0',
    appId: '1:31424277853:ios:c6f66c209ccdec3f4a8cb4',
    messagingSenderId: '31424277853',
    projectId: 'contador-calorias-b7dc8',
    storageBucket: 'contador-calorias-b7dc8.firebasestorage.app',
    iosBundleId: 'com.example.foodAnalyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl3FFMoOfMMDQK0jvb3BxeJr3v4OiaUy0',
    appId: '1:31424277853:ios:c6f66c209ccdec3f4a8cb4',
    messagingSenderId: '31424277853',
    projectId: 'contador-calorias-b7dc8',
    storageBucket: 'contador-calorias-b7dc8.firebasestorage.app',
    iosBundleId: 'com.example.foodAnalyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs6Y0UDuXRclDck6eyMT6h3yJ7k2o4CWg',
    appId: '1:31424277853:web:ea015d07a4dfb7634a8cb4',
    messagingSenderId: '31424277853',
    projectId: 'contador-calorias-b7dc8',
    authDomain: 'contador-calorias-b7dc8.firebaseapp.com',
    storageBucket: 'contador-calorias-b7dc8.firebasestorage.app',
    measurementId: 'G-TLYGCEH3E7',
  );

}